image: "python:3.7-buster"

variables:
  XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff

before_script:
  - pip install -r ./tools/requirements.txt
  - pip install requests
  - chmod +x ./build_all_rules.sh
  - chmod +x ./test_rules_import.py

build-sigma:
  stage: build
  script:
  - ./build_all_rules.sh
  artifacts:
    paths:
    - ./es-rules-output
    expire_in: 1 week

test-import:
  stage: test
  services:
  - name: elasticsearch:7.6.1
    alias: elasticsearch
    command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]
  - kibana:7.6.1
  tags:
  - kibana
  script:
  - python ./test_rules_import.py --kibana http://kibana:5601 --elasticsearch http://elasticsearch:9200
